# Generated by Django 4.2.7 on 2024-04-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="ads/image/", verbose_name="image"
            ),
        ),
    ]
