version: '3.8'

services:

  frontend:
    build: ../frontend_react/.
    volumes:
      - frontend:/app/build

  nginx:
    image: nginx:1.19.3
    ports:

      - "3000:3000"
    volumes:
      - ../skymarket/django_static/:/usr/share/nginx/html/django_static/
      - ../skymarket/django_media/:/usr/share/nginx/html/django_media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
    restart: always
    depends_on:

      - frontend

volumes:
  frontend: